[tool.poetry]
name = "netbox-documents"
version = "0.1.0"
description = ""
authors = ["Chris <crecio@hivedatacenter.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
